pipeline {
    agent any

    environment {
        COMPOSE_PROJECT_NAME = "chat-app"
    }

    stages {

       stage('Checkout') {
        steps {
            git branch: 'master',
                url: 'https://github.com/DevNetMohamed/Chat-App-Microservice-RabbitMQ',
                credentialsId: 'github-token'
        }
}

        stage('Build Docker Images') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Stop Old Containers') {
            steps {
                sh 'docker compose down'
            }
        }

        stage('Start Services') {
            steps {
                sh 'docker compose up -d'
            }
        }

        stage('Verify') {
            steps {
                sh 'docker ps'
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful '
        }
        failure {
            echo 'Deployment Failed'
        }
    }
}